---
- hosts: all
  vars:
    - user_db_1: ops1
    - user_db_2: ops2
    - user_web_3: ops3   
  sudo: yes
  
- name: Crear Grupos
  group:
    name: dbadmin, webadmin
    state: present
    
- name: create user ops1
  user: name={{ user_db_1 }} shell=/bin/bash
- name: create ssh dir
  file: path=/home/{{ dbadmin}}/.ssh state=directory
- name: chown and chmod of ssh dir
  file: path=/home/{{ dbadmin }}/.ssh recurse=yes
        owner={{ user_db_1}} group={{ dbadmin }} mode=0700
        state=directory
        
- name: create user ops2
  user: name={{ ops2 }} shell=/bin/bash
- name: create ssh dir
  file: path=/home/{{ dbadmin}}/.ssh state=directory
- name: chown and chmod of ssh dir
  file: path=/home/{{ dbadmin }}/.ssh recurse=yes
        owner={{ ops2 }} group={{ dbadmin }} mode=0700
        state=directory        
        
- name: create user ops3
  user: name={{ ops3 }} shell=/bin/bash
- name: create ssh dir
  file: path=/home/{{ webadmin}}/.ssh state=directory
- name: chown and chmod of ssh dir
  file: path=/home/{{ webadmin }}/.ssh recurse=yes
        owner={{ ops3 }} group={{ dbadmin }} mode=0700
        state=directory        
 
- name: copy sudoers file for safety
  command: cp -f /etc/sudoers /etc/sudoers.tmp
- name: add nopassword user
  lineinfile: dest=/etc/sudoers.tmp line="{{ ops3 }} ALL=(ALL:ALL) NOPASSWD:ALL"
- name: copy tmp file to real file with visudo check
  shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
  
