---
- name: Crear usuarios
  hosts: all
  become: yes
  vars:
    user_db_1: ops1
    user_db_2: ops2
    user_web_3: ops3 
    group_1: dbadmin
    group_2: webadmi
  tasks:
  - name: Crear Grupos 1
    group:
       name: dbadmin
       state: present
  
  - name: Crear Grupos 2
    group:
       name: webadmin
       state: present  
       
  - name: create user ops1
    user: name={{ user_db_1 }} shell=/bin/bash
  
  - name: create ssh dir
    file: path=/home/{{ user_db_1 }}/.ssh state=directory
  
  - name: chown and chmod of ssh dir
    file: path=/home/{{ user_db_1 }}/.ssh recurse=yes owner={{ user_db_1}} group={{ group_1 }} mode=0700 state=directory
        
  - name: create user ops2
    user: name={{ user_db_2 }} shell=/bin/bash

  - name: create ssh dir
    file: path=/home/{{ user_db_2 }}/.ssh state=directory

  - name: chown and chmod of ssh dir
    file: path=/home/{{ user_db_2 }}/.ssh recurse=yes owner={{ user_db_2 }} group={{ group_1}} mode=0700 state=directory        
        
  - name: create user ops3
    user: name={{ user_web_3 }} shell=/bin/bash
  
  - name: create ssh dir
    file: path=/home/{{ user_web_3 }}/.ssh state=directory

  - name: chown and chmod of ssh dir
    file: path=/home/{{ user_web_3 }}/.ssh recurse=yes owner={{ user_web_3 }} group={{ group_2 }} mode=0700 state=directory        
 
  - name: copy sudoers file for safety
    command: cp -f /etc/sudoers /etc/sudoers.tmp

  - name: add nopassword user
    lineinfile: dest=/etc/sudoers.tmp line="{{user_web_3 }} ALL=(ALL:ALL) NOPASSWD:ALL"
 
  - name: copy tmp file to real file with visudo check
    shell: visudo -q -c -f /etc/sudoers.tmp && cp -f /etc/sudoers.tmp /etc/sudoers
  
